### ISSUE TITLE
Have Documentation Identify FDM-9000 series STL and state their purpose

### ISSUE THREAD

**Issue by MakeItHackin** [index-machines/index#445] opened 2022-02-14 21:32 UTC
As a new user, I do not know what the FDM-9000 STL files are for and how to use them.  Suggest having a page in the documentation that goes over their use.  Thanks!

**Comment by atanisoft** [comment] 2022-02-14 21:41
The STL file names are not preserving the original file names as seen [here](https://github.com/index-machines/index/tree/v2.0.0/pnp/cad/FDM).

Similarly https://github.com/index-machines/index/blob/v2.0.0/pnp/cad/index_bom.md (which is referenced in the docs) should be linked and split by type (ie: only FDM files linked from docs) with a description of the part and matching STL filename.

**Comment by stuartpittaway** [comment] 2022-02-15 08:19
The STL filenames deliberately get renamed to match the internal part number (PN shape in FreeCad).  This is by design and part of the automated build processes.  Unfortunately this does mean the "descriptive" portion of the filename gets stripped off.

**Comment by ajw05002** [comment] 2022-02-16 03:56
the 9000 series FDM details are missing from the bom so I don't know quantity to print

**Comment by sphawes** [comment] 2022-03-08 22:58
This has been fixed in the v2.1.0 release!

**Closed by sphawes** 2022-03-08 22:58 UTC
Labels: documentation, triage
