### ISSUE TITLE
Missing motor specification for feeder

### ISSUE THREAD

**Issue by richardklingler** [index-machines/index#27] opened 2020-07-06 11:00 UTC
Hello

I don't see any specs about what motor is actually used for the feeders in the parts list nor in any description.

**Comment by raouldeheer** [comment] 2020-07-16 11:14
In [this video](https://www.youtube.com/watch?v=2foSlnGWeu0&list=PLIeJXmcg1baLBz3x0nCDqkYpKs2IWGHk4&index=6&t=0s) Stephen used a N20 Worm Gear Motor. I'm not sure which version but they're cheap so I would get the one with the most torque.
In [this video](https://www.youtube.com/watch?v=an5PXKHXsvQ&list=PLIeJXmcg1baLBz3x0nCDqkYpKs2IWGHk4&index=8) Stephen finds out that his N20 motor isn't strong enough to peel the tape. So he used an RC car motor, he doesn't says which motor it is.
I hope this information helped.

**Comment by G-Pereira** [comment] 2021-03-08 11:17
Hey @richardklingler !
Feeder motors used on our design are:
All-metal TT motors: https://www.aliexpress.com/item/33058637462.html
N20 50 rpm 6V: https://www.aliexpress.com/item/33022320164.html

We don't have assembly instructions or BOM for the feeder but we are working on it!

**Comment by sphawes** [comment] 2021-10-05 17:58
Thanks for the note @richardklingler! This is a duplicate of #63, closing.

**Closed by sphawes** 2021-10-05 17:58 UTC
Labels: documentation, duplicate, feeder
