### ISSUE TITLE
[BOM] - mobo-rev3 branch Ring Light BOM error (or wrong footprint)

### ISSUE THREAD

**Issue by arturo182** [index-machines/index#335] opened 2021-06-30 21:33 UTC
In the `mobo-rev3` branch the Ring Light BOM specifies the LCSC parts for the connector to be C146126 and C141812, which are 2.54mm and 2.50mm pitch respectively, however, the connector footprint is 2.00mm pitch.

Reference: https://github.com/index-machines/index/blob/mobo-rev03/pnp/pcb/ringLight/export/ringLight-bom.csv

The footprint specifies this connector: https://lcsc.com/product-detail/Wire-To-Board-Wire-To-Wire-Connector_JST-Sales-America-B3B-PH-SM4-TBT-LF-SN_C265082.html which, upon closer inspection, can't be the correct one because of the way the ring light mounts into the assembly:

![image](https://user-images.githubusercontent.com/249082/124034425-794c6300-d9fb-11eb-8a47-0f65f6cb123e.png)

It has to be a side entry connector, not top entry. If I'm correct, that would mean it should be this connector: https://lcsc.com/product-detail/Wire-To-Board-Wire-To-Wire-Connector_JST-Sales-America-S3B-PH-SM4-TB-LF-SN_C265101.html

On the other (third?) hand, is the pitch of the footprint correct? I wonder because on the mobo side the connector is a 2.50mm pitch XH-series.

I understand that it's a WIP branch so those values might be in there as a placeholder "like this, but not exactly", but I thought it might be good to have an Issue for this anyway, just so it's fixed eventually.

**Comment by G-Pereira** [comment] 2021-07-01 10:53
Thank you for pointing this out! I have both these connectors on order and I will check if they fit both the PCB and the print and decide what we'll do :)

**Comment by arturo182** [comment] 2021-07-01 17:05
Sorry, I wrote the pitch for C141812 wrong, it's 2.50mm, so neither of the two will fit the 2.00mm pitch, but if you have them in post then yes, good to validate 100%

**Comment by stuartpittaway** [comment] 2021-07-02 07:57
My LCSC delivery has already arrived with the parts in it - but looks like I didn't order the connectors for the ring light!

As a work around, it should be easy to solder wires directly to the ring light board.

**Comment by G-Pereira** [comment] 2021-07-03 10:57
@stuartpittaway I would say that is possible but you are risking tearing the pad from the PCB

**Comment by daveismith** [comment] 2021-07-03 11:55
You may want to use some hot glue and a zip tie to provide some strain
relief if you do that.

**Comment by arturo182** [comment] 2021-07-12 09:04
I have now received the side entry connector https://lcsc.com/product-detail/Wire-To-Board-Wire-To-Wire-Connector_JST-Sales-America-S3B-PH-SM4-TB-LF-SN_C265101.html and can confirm it does work with the case but doesn't match the footprint on the PCB. I mean, you can force it if you want it, but it's clearly a top-entry footprint:

![image](https://user-images.githubusercontent.com/249082/125260465-a4d72380-e300-11eb-94e2-4b94b1cd7c4e.png)
![image](https://user-images.githubusercontent.com/249082/125260505-ab659b00-e300-11eb-99bb-afee4eb678e2.png)
![image](https://user-images.githubusercontent.com/249082/125260571-c1735b80-e300-11eb-8087-91e5213269c3.png)

**Comment by G-Pereira** [comment] 2021-07-28 21:56
Confirmed this is not an issue.

**Comment by arturo182** [comment] 2021-07-29 00:46
Can you expand, cause the footprint doesn't match the part specified 😅

**Comment by G-Pereira** [comment] 2021-07-30 07:41
Right, although it is not an issue I will keep this open to denote the change

**Comment by G-Pereira** [comment] 2021-09-10 07:26
This has been fixed by changing the connector to a XH through hole!

**Closed by G-Pereira** 2021-09-10 07:26 UTC
Labels: bug, requires validation, pcb
